#!/bin/bash
### BEGIN INIT INFO
# Provides:          webapp_startup
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This file is a service for webapp. The script should be placed in /etc/init.d                   
### END INIT INFO

case "$1" in 
start)
   python /path_to_webapp_folder/Main.py --project_id=cloud-iot-testing-185623 --registry_id=cloud-iot-registry1 --device_id=iot-device1 --algorithm=RS256 --private_key_file=/path_to_webapp_folder/PemFiles/rsa_private.pem --public_key_file=/path_to_webapp_folder/PemFiles/rsa_cert.pem --credential=/path_to_webapp_folder/PemFiles/cloud-iot-testing-052b9ca41b45.json --cloud_region=us-central1 --pubsub_topic=cloud-iot-topic1  --message_type=event --message_data_type=image_string &
   echo $!>/var/run/webapp.pid
   ;;
stop)
   kill `cat /var/run/webapp.pid`
   rm /var/run/webapp.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/webapp.pid ]; then
      pid=`cat /var/run/webapp.pid`
      echo "webapp is running on process id: ${pid}" 
   else
      echo "webapp is NOT running"
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
